### PR TITLE
Route guide example simplification

### PR DESCRIPTION
**Pull request by alanraul**
### What did I do?

- code documentation
- README documentation
- separate content from route_guide protobuf
- code simplification

### CODE REVIEW

**Comment by tony612** [comment]
I don't think it's necessary to change much:
* proto is same with this https://github.com/grpc/grpc/blob/master/examples/protos/route_guide.proto, so we don't want to write it by hand. And also for https://github.com/grpc/grpc/blob/master/examples/cpp/route_guide/route_guide_db.json
* There's already `protoc` command in the README now.
* There's no need to create folders for client.ex, data.ex and so on.

I think we only need to add more logs to client.ex if you want to.

**Comment by tony612** [comment]
Please rebase/merge master.

**Comment by danielwillemse** [comment]
Any chance this could get rebased/merged, so it can be merged? @alanraul 
I think the examples and documentation are really valuable.
Seeing as the current master is missing examples for features like streams and bidirectional streams.

**Comment by polvalente** [comment]
@alanraul Is this still relevant? If so, please update the branch.

**Comment by polvalente** [comment]
Closing this because it had been stale with changes requested even around the time it was opened.

**Pull request closed without merging**
