### PR TITLE
Relax cowboy version constraint from 2.7.0 to 2.7

### PR DESCRIPTION
**Pull request by hkrutzer**

### CODE REVIEW

**Comment by nonninz** [comment]
Seconded. This solves dependency problems that would prevent us to use `cowlib ~> 2.9` as advised [in this same project's README](https://github.com/elixir-grpc/grpc#installation)

**Comment by hkrutzer** [comment]
@tony612 do you have time to merge this?

**Review by redink — APPROVED** [review]

**Comment by tony612** [comment]
Merged. Thanks!

**Comment by hkrutzer** [comment]
Thank you!

**Comment by rmertzpfpt** [comment]
When will this change make its way to `hexpm`? In my project, I'm required to use this lib via `hexpm` (where it is still `2.7.0`) as opposed to pulling it as a `git` dependency.

**Pull request merged**
