### PR TITLE
Default read timeout is :infinity

### PR DESCRIPTION
**Pull request by mairbek**
Potential fix for https://github.com/elixir-grpc/grpc/issues/141

### CODE REVIEW

**Comment by isaacsanders** [comment]
Should this not just be configurable from public interface? Defaulting to infinity feels broken.

**Comment by prydonius** [comment]
The gRPC protocol suggests that the default should be infinity:

> If Timeout is omitted a server should assume an infinite timeout. Client implementations are free to send a default minimum timeout based on their deployment requirements.

https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

**Comment by tony612** [comment]
@isaacsanders I think it's okay to use `infinity` here because it's used only when no timer is set, which means clients doesn't specify a timeout.

**Comment by tony612** [comment]
I created a PR to set default timeout to `:infinity` only for streaming calls. Please leave some comments.

**Pull request merged**
