### PR TITLE
ci: run interop test on PR and master branch

### LINKED ISSUE #223: [CI] Run Interop tests in with the version matrix
Currently, our interop tests only run in a specific Elixir 1.9 image.
I think it would be better to run them in a version matrix like the unit tests. Since they take long, perhaps we can use either a reduced matrix or just run them in the main branch

### PR DESCRIPTION
**Pull request by wingyplus**
The pipeline will be:

On Pull Request:

Screen Shot 2565-07-21 at 14 31 00

The interop-test-all will be skip. You can see at https://github.com/wingyplus/grpc/actions/runs/2710073388.

And when merging to master branch: 

Screen Shot 2565-07-21 at 14 32 13

The interop-test will be skipped and running interop-test-all which running all version of OTP/Elixir. You can see at https://github.com/wingyplus/grpc/actions/runs/2710090462.

Closes #223

### CODE REVIEW

**Comment by polvalente** [comment]
Is this a draft because you will still add the matrix for interop on main?

**Comment by wingyplus** [comment]
> Is this a draft because you will still add the matrix for interop on main?

Yes. I still working on it. :)

**Comment by wingyplus** [comment]
@polvalente This PR is ready to review. I explain the detail in the PR description above. Feel free to comment. :)

**Comment by wingyplus** [comment]
I guess that we don't need cron_ci.yaml since it run every commit that merge to master branch?

**Comment by polvalente** [comment]
> I guess that we don't need cron_ci.yaml since it run every commit that merge to master branch? 

Yes. We can just rework the main workflow to run whatever is missing from the workflow.

Perhaps we can get rid of that .ci directory and script as well

**Review by polvalente — APPROVED** [review]

**Pull request merged**
