### PR TITLE
[WIP] Support error details

### LINKED ISSUE #109: Sending error details to the client side
Hi guys, I was going through the code trying to learn what is the implemented way of sending error details as seen in [https://cloud.google.com/apis/design/errors](https://cloud.google.com/apis/design/errors) but I couldn't find anything. How you guys are sending things like validation errors, localized messages and other relevant error information.

### PR DESCRIPTION
**Pull request by tony612**
Fixes #109

### CODE REVIEW

**Comment by tony612** [comment]
I know this problem, I plan to do so. But the problem is there's not a good way to encode/decode `google.protobuf.Any`, so I paused this PR. Let me revisit this again after I make more progress in protobuf side.

**Comment by tony612** [comment]
btw, the reason why handling `google.protobuf.Any` is hard is there's no native support for global registering in runtime like https://github.com/protocolbuffers/protobuf-go/blob/master/types/known/anypb/any.pb.go#L250. I implemented a similar thing recently in https://github.com/tony612/protobuf-elixir/pull/83/files#diff-343d0a95ba21cab58868d21213e1ac67R13, which probably can solve this problem.

**Comment by darrenclark** [comment]
Cool, thanks for the update!  Feel free to reach out if you want help with anything.

**Comment by imcosta** [comment]
Hi @tony612 👋  Any update about this? Could you find a good way to encode/decode the `google.protobuf.Any`?

**Comment by polvalente** [comment]
Closing this as stale for now

**Comment by ddengler** [comment]
Sadly just seen this closed. Also just ran into this again. Anything I can do to support here?

**Comment by yordis** [comment]
After https://github.com/elixir-protobuf/protobuf/pull/409 hopefully this work can be done

**Comment by yordis** [comment]
I am giving it another try: https://github.com/elixir-grpc/grpc/pull/442

**Pull request closed without merging**
